### ISSUE TITLE
Is there a compiler/compiler version that is prefered ?

### ISSUE THREAD

**Issue by mboisson** [BIC-MNI/minc-toolkit-v2#63]
I am getting compilation errors whether I compile with GCC 5.4.0 or Intel 2016.4 : 

With GCC 5.4.0 : 

```
                                                    ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2486:31: error: unknown type name ‘opj_cio_t’
 static void OPJ_CALLCONV (*_opj_cio_close)(opj_cio_t *);
                               ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2487:40: error: unknown type name ‘opj_dinfo_t’
 static void OPJ_CALLCONV (*_opj_destroy_decompress)(opj_dinfo_t *);
                                        ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2499:16: error: ‘_opj_setup_decoder’ undeclared here (not in a function)
   { (void **) &_opj_setup_decoder, "opj_setup_decoder" },
                ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2500:16: error: ‘_opj_decode’ undeclared here (not in a function)
   { (void **) &_opj_decode, "opj_decode" },
                ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2501:16: error: ‘_opj_cio_open’ undeclared here (not in a function)
   { (void **) &_opj_cio_open, "opj_cio_open" },
                ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2502:16: error: ‘_opj_cio_close’ undeclared here (not in a function)
   { (void **) &_opj_cio_close, "opj_cio_close" },
                ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2503:16: error: ‘_opj_destroy_decompress’ undeclared here (not in a function)
   { (void **) &_opj_destroy_decompress, "opj_destroy_decompress"},
                ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c: In function ‘dicom_opj_decompress’:
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2544:3: error: unknown type name ‘opj_dinfo_t’
   opj_dinfo_t *dinfo;
   ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2545:3: error: unknown type name ‘opj_cio_t’
   opj_cio_t *cio;
   ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2558:39: error: ‘CODEC_J2K’ undeclared (first use in this function)
   if ((dinfo = _opj_create_decompress(CODEC_J2K)) == NULL) {
                                       ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2558:39: note: each undeclared identifier is reported only once for each function it appears in
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2558:39: error: incompatible type for argument 1 of ‘_opj_create_decompress’
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2558:39: note: expected ‘OPJ_CODEC_FORMAT {aka enum CODEC_FORMAT}’ but argument is of type ‘struct <anonymous> *’
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2558:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   if ((dinfo = _opj_create_decompress(CODEC_J2K)) == NULL) {
              ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2562:3: warning: implicit declaration of function ‘_opj_setup_decoder’ [-Wimplicit-function-declaration]
   _opj_setup_decoder(dinfo, &dparameters);
   ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2563:9: warning: implicit declaration of function ‘_opj_cio_open’ [-Wimplicit-function-declaration]
   cio = _opj_cio_open((opj_common_ptr) dinfo, jpg_buffer, jpg_size);
         ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2563:24: error: ‘opj_common_ptr’ undeclared (first use in this function)
   cio = _opj_cio_open((opj_common_ptr) dinfo, jpg_buffer, jpg_size);
                        ^
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/GCC-5.4.0/minc-toolkit-v2-1.9.16/minctools/conversion/dcm2mnc/dicom_read.c:2563:40: error: expected ‘)’ before ‘dinfo’
``` 

or with Intel : 
```
[ 35%] Building CXX object mrisim/CMakeFiles/mrisim.dir/src/minc/chirp.cxx.o
cd /dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/easybuild_obj/mrisim && /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/ccache /tmp/eb-C3UHzQ/tmp3PcscZ/icpc  -DHAVE_CONFIG_H -DHAVE_MINC1=1 -DHAVE_MINC2=1 -DMINC2=1 -D_XOPEN_SOURCE=500 -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/libminc -I/dev/shm/   mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/libminc/libcommon -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/libminc/libsrc2 -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/libminc/volume_io/Include -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc- toolkit-v2-1.9.16/libminc/libsrc -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/libminc/ezminc -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/easybuild_obj/external/home/mboisson/.local/easybuild/software/2017/avx2/Compiler/intel2016.4/minc-toolkit/1.9.16/include -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/       iccifort-2016.4/minc-toolkit-v2-1.9.16/EBTKS/include -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/EBTKS/templates -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/bicpl/Include -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/arguments/src -I/dev/shm/       mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/oobicpl/src -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/easybuild_obj/mrisim -I/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/mrisim/src  -O2 -xCore-AVX2 -ftz -fp-speculation=safe -fp-model source -O3 -DNDEBUG   -o CMakeFiles/mrisim.dir/src/ minc/chirp.cxx.o -c /dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/mrisim/src/minc/chirp.cxx
/dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/EBTKS/templates/Matrix.cc(35): error: cannot determine which instance of overloaded function "Mat<Type>::applyIndexFunction [with Type=dcomplex]" is intended
  #pragma do_not_instantiate Mat<dcomplex>::applyIndexFunction
                             ^

compilation aborted for /dev/shm/mboisson/avx2/MINCToolkit/1.9.16/iccifort-2016.4/minc-toolkit-v2-1.9.16/EBTKS/templates/Matrix.cc (code 2)
```

**Comment by vfonov** [comment]
for gcc  - it didn't find right version of openJpeg , I didn't try using Intel compiler

**Comment by gdevenyi** [comment]
Regarding intel, removing the failing line fixes things, see https://github.com/BIC-MNI/EBTKS/issues/2

In general, I've build minc-toolkit-v2 using multiple versions of gcc (4-7) and intel with no problems (except previously mentioned fix)

**Comment by mboisson** [comment]
What version of openJpeg would it need ? 
It did find jpeg libraries : 
```
[mboisson@build-node easybuild_obj]$ grep -i jpeg CMakeCache.txt
JPEG_INCLUDE_DIR:PATH=/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include
JPEG_LIBRARY:FILEPATH=/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libjpeg.so
//Location of OpenJPEG Headers
OPENJPEG_INCLUDE_DIR:PATH=/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include/openjpeg-2.1
OPENJPEG_LIBRARY:FILEPATH=/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libopenjp2.so
//Details about finding JPEG
FIND_PACKAGE_MESSAGE_DETAILS_JPEG:INTERNAL=[/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libjpeg.so][/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include][v()]
//ADVANCED property for variable: JPEG_INCLUDE_DIR
JPEG_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: JPEG_LIBRARY
JPEG_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENJPEG_INCLUDE_DIR
OPENJPEG_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENJPEG_LIBRARY
OPENJPEG_LIBRARY-ADVANCED:INTERNAL=1
```

**Comment by vfonov** [comment]
If you can take a look here, for example: https://github.com/vfonov/conda-recipes/tree/master/minc-toolkit-v2

**Comment by mboisson** [comment]
My point is that it did find OpenJPEG, 2.1. Are you saying that this is not enough ? I see your example uses OpenJPEG 2.3. Is that the issue ?

**Comment by vfonov** [comment]
I am not sure , 1.9.16 included older version of minc-tools that used undocumented interface to OpenJPEG. It was rewritten and 1.9.17 is made to work properly with OpenJpeg of different versions:
https://github.com/BIC-MNI/minc-tools/commit/bcc03a352f10cee18af26a8208c82a494202bcc8

**Comment by mboisson** [comment]
It looks like installing OpenJPEG 2.3 helped. I'll try with that and with Intel. 

@vfonov, I see that your example uses dependencies from Conda, while the recommendation on MINC's README is to not use external dependencies.

Are there some that are safe to use from external ? We already have most of the dependencies pre-compiled as modules.

**Comment by vfonov** [comment]
it is experimental, YMMV

**Comment by vfonov** [comment]
1.9.16 will not properly build with system libraries, most likely.

**Comment by mboisson** [comment]
Ok, thanks.
