### ISSUE TITLE
LIbminc compilation error introduced on develop-1.9.18

### ISSUE THREAD

**Issue by bcdarwin** [BIC-MNI/minc-toolkit-v2#147]
I have run into the following `libminc` compilation error [Ubuntu 20.04, GCC 9.4.0, stock configuration but with building shared libs enabled] which according to `git bisect` was introduced by a `libminc` bump (f3e6e8c6):

```
Consolidate compiler generated dependencies of target _minctracc
[ 31%] Building C object mni_autoreg/minctracc/CMakeFiles/_minctracc.dir/Optimize/extras.c.o
In file included from /home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c:18:
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c: In function ‘save_data’:
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Include/local_macros.h:22:41: error: expected ‘)’ before ‘_ALLOC_SOURCE_LINE’
   22 |                          sizeof(*(ptr)) _ALLOC_SOURCE_LINE )
      |                                         ^~~~~~~~~~~~~~~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c:177:3: note: in expansion of macro ‘ALLOC’
  177 |   ALLOC(comments, 512);
      |   ^~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Include/local_macros.h:22:41: error: expected ‘)’ before ‘_ALLOC_SOURCE_LINE’
   22 |                          sizeof(*(ptr)) _ALLOC_SOURCE_LINE )
      |                                         ^~~~~~~~~~~~~~~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c:178:3: note: in expansion of macro ‘ALLOC’
  178 |   ALLOC(name, 512);
      |   ^~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Include/local_macros.h:30:37: error: expected ‘)’ before ‘_ALLOC_SOURCE_LINE’
   30 |    free_memory_1d( (void **) &(ptr) _ALLOC_SOURCE_LINE )
      |                                     ^~~~~~~~~~~~~~~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c:199:3: note: in expansion of macro ‘FREE’
  199 |   FREE(name);
      |   ^~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Include/local_macros.h:30:37: error: expected ‘)’ before ‘_ALLOC_SOURCE_LINE’
   30 |    free_memory_1d( (void **) &(ptr) _ALLOC_SOURCE_LINE )
      |                                     ^~~~~~~~~~~~~~~~~~
/home/bdarwin/git/minc-toolkit-v2/mni_autoreg/minctracc/Optimize/extras.c:200:3: note: in expansion of macro ‘FREE’
  200 |   FREE(comments);
      |   ^~~~
make[2]: *** [mni_autoreg/minctracc/CMakeFiles/_minctracc.dir/build.make:104: mni_autoreg/minctracc/CMakeFiles/_minctracc.dir/Optimize/extras.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:12630: mni_autoreg/minctracc/CMakeFiles/_minctracc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Built target bicpl_static
make: *** [Makefile:166: all] Error 2
```

Perhaps this belongs on the `libminc` issue tracker but I didn't see anything there either.

I'll try to take a look if I have a chance but we'll see -- it's not really urgent for me at the moment.

**Comment by gdevenyi** [comment]
Fixed at https://github.com/BIC-MNI/mni_autoreg/commit/e34240fa9d13b06e49e4f2accf7d8681c987f397 and pending merge #154
